#!/bin/sh

######################################################################
# Initial Configuration
######################################################################

# === Initialize shell environment ===================================
set -u
umask 0022
export LC_ALL=C

PATH="$(command -p getconf PATH 2>/dev/null)${PATH+:}${PATH-}"
export PATH
case $PATH in :*) PATH=${PATH#?} ;; esac
export UNIX_STD=2003 # to make HP-UX conform to POSIX

# === Define the functions for printing usage and error message ======
print_usage_and_exit() {
	cat <<-USAGE 1>&2
		Usage   : ${0##*/} <filename> 

		Version : Sun 29 May 2022 12:19:36 PM JST
	USAGE
	exit 1
}

error_exit() {
	${2+:} false && echo "${0##*/}: $2" 1>&2
	exit "$1"
}

# === Print usage and exit if one of the help options is set =========
case "$# ${1:-}" in
'1 -h' | '1 --help' | '1 --version') print_usage_and_exit ;;
esac

######################################################################
# Main Routine
######################################################################

if [ ! -f "$1" ]; then error_exit 1 "$1 is not a file or doesn't exist"; fi

tempfile="$(mktemp "${0##*/}.$$.XXXXXXXXXXX.go")" || error_exit 1 'Failed to mktemp'
trap '[ -f "${tempfile}" ] && rm "${tempfile}"' EXIT

main_func="main_${1%.*}"
package_name="$(sed -n -e '/package /p' "$1" | sed -e 's;package\s\s*;;')"

cat <<EOF > "$tempfile"
package ${package_name}

func main() {
	${main_func}()
}
EOF

go build && "./${package_name}" && rm "${package_name}"

######################################################################
# Finish
######################################################################

exit 0
